default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: hello_rails_react_development
  username: postgres
  password: 1378

test:
  <<: *default
  database: hello_rails_react_test
  username: postgres
  password: 1378

production:
  <<: *default
  database: hello_rails_react_production
  username: postgres
  password: 1378

